import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import DynamicSidebar from "@/components/DynamicSidebar/DynamicSidebar";
import Template from "./template";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bodyBackground`}>
        <Header />
        <div className="flex flex-col items-center lg:flex-row px-4 lg:items-start lg:gap-[70px]  mt-4 sm:px-3 md:pl-8  lg:w-11/12">
          <Template>
            <DynamicSidebar />
          </Template>
          <div className=" w-full flex justify-center">{children}</div>
        </div>
      </body>
    </html>
  );
}
